import "./home.scss";
import {Navbar} from "../components/navbar/Navbar";

export const Home = () => {
    return (
        <div className={"home"}>
            <Navbar />
               <img width="100%" src="https://cdn.mos.cms.futurecdn.net/AT9Bcvo94cTMGmESvL4JCK-970-80.jpg.webp" alt="photo"/>
           Risus recteque fringilla epicurei gravida definitiones. Diam expetendis felis vidisse vestibulum quidam mel porro ex sapien. Suscipiantur mea voluptatibus conubia efficiantur singulis. Quaeque postea veri eleifend neglegentur principes interpretaris quod. Persequeris audire constituam appetere aliquid mucius.
           Risus recteque fringilla epicurei gravida definitiones. Diam expetendis felis vidisse vestibulum quidam mel porro ex sapien. Suscipiantur mea voluptatibus conubia efficiantur singulis. Quaeque postea veri eleifend neglegentur principes interpretaris quod. Persequeris audire constituam appetere aliquid mucius.
           Risus recteque fringilla epicurei gravida definitiones. Diam expetendis felis vidisse vestibulum quidam mel porro ex sapien. Suscipiantur mea voluptatibus conubia efficiantur singulis. Quaeque postea veri eleifend neglegentur principes interpretaris quod. Persequeris audire constituam appetere aliquid mucius.
           Risus recteque fringilla epicurei gravida definitiones. Diam expetendis felis vidisse vestibulum quidam mel porro ex sapien. Suscipiantur mea voluptatibus conubia efficiantur singulis. Quaeque postea veri eleifend neglegentur principes interpretaris quod. Persequeris audire constituam appetere aliquid mucius.
           Risus recteque fringilla epicurei gravida definitiones. Diam expetendis felis vidisse vestibulum quidam mel porro ex sapien. Suscipiantur mea voluptatibus conubia efficiantur singulis. Quaeque postea veri eleifend neglegentur principes interpretaris quod. Persequeris audire constituam appetere aliquid mucius.
           Risus recteque fringilla epicurei gravida definitiones. Diam expetendis felis vidisse vestibulum quidam mel porro ex sapien. Suscipiantur mea voluptatibus conubia efficiantur singulis. Quaeque postea veri eleifend neglegentur principes interpretaris quod. Persequeris audire constituam appetere aliquid mucius.
           Risus recteque fringilla epicurei gravida definitiones. Diam expetendis felis vidisse vestibulum quidam mel porro ex sapien. Suscipiantur mea voluptatibus conubia efficiantur singulis. Quaeque postea veri eleifend neglegentur principes interpretaris quod. Persequeris audire constituam appetere aliquid mucius.
           Risus recteque fringilla epicurei gravida definitiones. Diam expetendis felis vidisse vestibulum quidam mel porro ex sapien. Suscipiantur mea voluptatibus conubia efficiantur singulis. Quaeque postea veri eleifend neglegentur principes interpretaris quod. Persequeris audire constituam appetere aliquid mucius.
           Risus recteque fringilla epicurei gravida definitiones. Diam expetendis felis vidisse vestibulum quidam mel porro ex sapien. Suscipiantur mea voluptatibus conubia efficiantur singulis. Quaeque postea veri eleifend neglegentur principes interpretaris quod. Persequeris audire constituam appetere aliquid mucius.
           Risus recteque fringilla epicurei gravida definitiones. Diam expetendis felis vidisse vestibulum quidam mel porro ex sapien. Suscipiantur mea voluptatibus conubia efficiantur singulis. Quaeque postea veri eleifend neglegentur principes interpretaris quod. Persequeris audire constituam appetere aliquid mucius.
           Risus recteque fringilla epicurei gravida definitiones. Diam expetendis felis vidisse vestibulum quidam mel porro ex sapien. Suscipiantur mea voluptatibus conubia efficiantur singulis. Quaeque postea veri eleifend neglegentur principes interpretaris quod. Persequeris audire constituam appetere aliquid mucius.
           Risus recteque fringilla epicurei gravida definitiones. Diam expetendis felis vidisse vestibulum quidam mel porro ex sapien. Suscipiantur mea voluptatibus conubia efficiantur singulis. Quaeque postea veri eleifend neglegentur principes interpretaris quod. Persequeris audire constituam appetere aliquid mucius.
           Risus recteque fringilla epicurei gravida definitiones. Diam expetendis felis vidisse vestibulum quidam mel porro ex sapien. Suscipiantur mea voluptatibus conubia efficiantur singulis. Quaeque postea veri eleifend neglegentur principes interpretaris quod. Persequeris audire constituam appetere aliquid mucius.
           Risus recteque fringilla epicurei gravida definitiones. Diam expetendis felis vidisse vestibulum quidam mel porro ex sapien. Suscipiantur mea voluptatibus conubia efficiantur singulis. Quaeque postea veri eleifend neglegentur principes interpretaris quod. Persequeris audire constituam appetere aliquid mucius.
           Risus recteque fringilla epicurei gravida definitiones. Diam expetendis felis vidisse vestibulum quidam mel porro ex sapien. Suscipiantur mea voluptatibus conubia efficiantur singulis. Quaeque postea veri eleifend neglegentur principes interpretaris quod. Persequeris audire constituam appetere aliquid mucius.
           Risus recteque fringilla epicurei gravida definitiones. Diam expetendis felis vidisse vestibulum quidam mel porro ex sapien. Suscipiantur mea voluptatibus conubia efficiantur singulis. Quaeque postea veri eleifend neglegentur principes interpretaris quod. Persequeris audire constituam appetere aliquid mucius.
           Risus recteque fringilla epicurei gravida definitiones. Diam expetendis felis vidisse vestibulum quidam mel porro ex sapien. Suscipiantur mea voluptatibus conubia efficiantur singulis. Quaeque postea veri eleifend neglegentur principes interpretaris quod. Persequeris audire constituam appetere aliquid mucius.
           Risus recteque fringilla epicurei gravida definitiones. Diam expetendis felis vidisse vestibulum quidam mel porro ex sapien. Suscipiantur mea voluptatibus conubia efficiantur singulis. Quaeque postea veri eleifend neglegentur principes interpretaris quod. Persequeris audire constituam appetere aliquid mucius.
           Risus recteque fringilla epicurei gravida definitiones. Diam expetendis felis vidisse vestibulum quidam mel porro ex sapien. Suscipiantur mea voluptatibus conubia efficiantur singulis. Quaeque postea veri eleifend neglegentur principes interpretaris quod. Persequeris audire constituam appetere aliquid mucius.
           Risus recteque fringilla epicurei gravida definitiones. Diam expetendis felis vidisse vestibulum quidam mel porro ex sapien. Suscipiantur mea voluptatibus conubia efficiantur singulis. Quaeque postea veri eleifend neglegentur principes interpretaris quod. Persequeris audire constituam appetere aliquid mucius.
           Risus recteque fringilla epicurei gravida definitiones. Diam expetendis felis vidisse vestibulum quidam mel porro ex sapien. Suscipiantur mea voluptatibus conubia efficiantur singulis. Quaeque postea veri eleifend neglegentur principes interpretaris quod. Persequeris audire constituam appetere aliquid mucius.
           Risus recteque fringilla epicurei gravida definitiones. Diam expetendis felis vidisse vestibulum quidam mel porro ex sapien. Suscipiantur mea voluptatibus conubia efficiantur singulis. Quaeque postea veri eleifend neglegentur principes interpretaris quod. Persequeris audire constituam appetere aliquid mucius.
           Risus recteque fringilla epicurei gravida definitiones. Diam expetendis felis vidisse vestibulum quidam mel porro ex sapien. Suscipiantur mea voluptatibus conubia efficiantur singulis. Quaeque postea veri eleifend neglegentur principes interpretaris quod. Persequeris audire constituam appetere aliquid mucius.
           Risus recteque fringilla epicurei gravida definitiones. Diam expetendis felis vidisse vestibulum quidam mel porro ex sapien. Suscipiantur mea voluptatibus conubia efficiantur singulis. Quaeque postea veri eleifend neglegentur principes interpretaris quod. Persequeris audire constituam appetere aliquid mucius.
           Risus recteque fringilla epicurei gravida definitiones. Diam expetendis felis vidisse vestibulum quidam mel porro ex sapien. Suscipiantur mea voluptatibus conubia efficiantur singulis. Quaeque postea veri eleifend neglegentur principes interpretaris quod. Persequeris audire constituam appetere aliquid mucius.
           Risus recteque fringilla epicurei gravida definitiones. Diam expetendis felis vidisse vestibulum quidam mel porro ex sapien. Suscipiantur mea voluptatibus conubia efficiantur singulis. Quaeque postea veri eleifend neglegentur principes interpretaris quod. Persequeris audire constituam appetere aliquid mucius.
           Risus recteque fringilla epicurei gravida definitiones. Diam expetendis felis vidisse vestibulum quidam mel porro ex sapien. Suscipiantur mea voluptatibus conubia efficiantur singulis. Quaeque postea veri eleifend neglegentur principes interpretaris quod. Persequeris audire constituam appetere aliquid mucius.
           Risus recteque fringilla epicurei gravida definitiones. Diam expetendis felis vidisse vestibulum quidam mel porro ex sapien. Suscipiantur mea voluptatibus conubia efficiantur singulis. Quaeque postea veri eleifend neglegentur principes interpretaris quod. Persequeris audire constituam appetere aliquid mucius.
           Risus recteque fringilla epicurei gravida definitiones. Diam expetendis felis vidisse vestibulum quidam mel porro ex sapien. Suscipiantur mea voluptatibus conubia efficiantur singulis. Quaeque postea veri eleifend neglegentur principes interpretaris quod. Persequeris audire constituam appetere aliquid mucius.
           Risus recteque fringilla epicurei gravida definitiones. Diam expetendis felis vidisse vestibulum quidam mel porro ex sapien. Suscipiantur mea voluptatibus conubia efficiantur singulis. Quaeque postea veri eleifend neglegentur principes interpretaris quod. Persequeris audire constituam appetere aliquid mucius.
           Risus recteque fringilla epicurei gravida definitiones. Diam expetendis felis vidisse vestibulum quidam mel porro ex sapien. Suscipiantur mea voluptatibus conubia efficiantur singulis. Quaeque postea veri eleifend neglegentur principes interpretaris quod. Persequeris audire constituam appetere aliquid mucius.
           Risus recteque fringilla epicurei gravida definitiones. Diam expetendis felis vidisse vestibulum quidam mel porro ex sapien. Suscipiantur mea voluptatibus conubia efficiantur singulis. Quaeque postea veri eleifend neglegentur principes interpretaris quod. Persequeris audire constituam appetere aliquid mucius.
           Risus recteque fringilla epicurei gravida definitiones. Diam expetendis felis vidisse vestibulum quidam mel porro ex sapien. Suscipiantur mea voluptatibus conubia efficiantur singulis. Quaeque postea veri eleifend neglegentur principes interpretaris quod. Persequeris audire constituam appetere aliquid mucius.
           Risus recteque fringilla epicurei gravida definitiones. Diam expetendis felis vidisse vestibulum quidam mel porro ex sapien. Suscipiantur mea voluptatibus conubia efficiantur singulis. Quaeque postea veri eleifend neglegentur principes interpretaris quod. Persequeris audire constituam appetere aliquid mucius.
           Risus recteque fringilla epicurei gravida definitiones. Diam expetendis felis vidisse vestibulum quidam mel porro ex sapien. Suscipiantur mea voluptatibus conubia efficiantur singulis. Quaeque postea veri eleifend neglegentur principes interpretaris quod. Persequeris audire constituam appetere aliquid mucius.
           Risus recteque fringilla epicurei gravida definitiones. Diam expetendis felis vidisse vestibulum quidam mel porro ex sapien. Suscipiantur mea voluptatibus conubia efficiantur singulis. Quaeque postea veri eleifend neglegentur principes interpretaris quod. Persequeris audire constituam appetere aliquid mucius.
           Risus recteque fringilla epicurei gravida definitiones. Diam expetendis felis vidisse vestibulum quidam mel porro ex sapien. Suscipiantur mea voluptatibus conubia efficiantur singulis. Quaeque postea veri eleifend neglegentur principes interpretaris quod. Persequeris audire constituam appetere aliquid mucius.
           Risus recteque fringilla epicurei gravida definitiones. Diam expetendis felis vidisse vestibulum quidam mel porro ex sapien. Suscipiantur mea voluptatibus conubia efficiantur singulis. Quaeque postea veri eleifend neglegentur principes interpretaris quod. Persequeris audire constituam appetere aliquid mucius.
           Risus recteque fringilla epicurei gravida definitiones. Diam expetendis felis vidisse vestibulum quidam mel porro ex sapien. Suscipiantur mea voluptatibus conubia efficiantur singulis. Quaeque postea veri eleifend neglegentur principes interpretaris quod. Persequeris audire constituam appetere aliquid mucius.
           Risus recteque fringilla epicurei gravida definitiones. Diam expetendis felis vidisse vestibulum quidam mel porro ex sapien. Suscipiantur mea voluptatibus conubia efficiantur singulis. Quaeque postea veri eleifend neglegentur principes interpretaris quod. Persequeris audire constituam appetere aliquid mucius.
           Risus recteque fringilla epicurei gravida definitiones. Diam expetendis felis vidisse vestibulum quidam mel porro ex sapien. Suscipiantur mea voluptatibus conubia efficiantur singulis. Quaeque postea veri eleifend neglegentur principes interpretaris quod. Persequeris audire constituam appetere aliquid mucius.
           Risus recteque fringilla epicurei gravida definitiones. Diam expetendis felis vidisse vestibulum quidam mel porro ex sapien. Suscipiantur mea voluptatibus conubia efficiantur singulis. Quaeque postea veri eleifend neglegentur principes interpretaris quod. Persequeris audire constituam appetere aliquid mucius.
           Risus recteque fringilla epicurei gravida definitiones. Diam expetendis felis vidisse vestibulum quidam mel porro ex sapien. Suscipiantur mea voluptatibus conubia efficiantur singulis. Quaeque postea veri eleifend neglegentur principes interpretaris quod. Persequeris audire constituam appetere aliquid mucius.
           Risus recteque fringilla epicurei gravida definitiones. Diam expetendis felis vidisse vestibulum quidam mel porro ex sapien. Suscipiantur mea voluptatibus conubia efficiantur singulis. Quaeque postea veri eleifend neglegentur principes interpretaris quod. Persequeris audire constituam appetere aliquid mucius.
        </div>
    )
}